name: diffusers
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pywin32  
  - pip:
    - opencv-python
    - transformers
    - scipy
    - ftfy
    - tqdm
    - ipywidgets==7.7.1    
    - Pillow==9.0.0
    - basicsr>=1.4.2
    - gfpgan>=1.3.5
    - facexlib>=0.2.5
    - -e git+https://github.com/huggingface/diffusers.git@main#egg=diffusers    
    - -e git+https://github.com/xinntao/Real-ESRGAN.git@master#egg=realesrgan
