!!python/object:__main__.Namespace
ckpt_loc: models/ldm/stable-diffusion-v1/model.ckpt
config: configs/stable-diffusion/v1-inference.yaml
out_dir: output

embeddings:  
  #- token: '<my-face>'
  #  file: C:\Users\gamma\Documents\development\diffusers-gui\data\embeddings\my_face3.pt  
  - token: '<chaz>'
    file: C:\dev\embeddings\chaz2.bin